pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Semantic Pull Request
    actions:
      merge:
        method: merge
